apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: foundryvtt-tls-certificate
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  commonName: foundry.hyperion.law
  secretName: foundryvtt-tls-certificate
  dnsNames:
    - foundry.hyperion.law
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer