apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundryvtt-edgerunners
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: foundryvtt
    foundryvtt/world: edgerunners
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: foundryvtt
      foundryvtt/world: edgerunners
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foundryvtt
        foundryvtt/world: edgerunners
    spec:
      serviceAccountName: foundryvtt
      initContainers:
        - name: iptables
          image: trow.hyperion.law/init-proxy:latest
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: true
      containers:
        - name: foundryvtt-edgerunners
          image: trow.hyperion.law/foundryvtt:10.291.0
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: foundryvtt-secrets
          env:
            - name: FOUNDRY_HOSTNAME
              value: foundry.hyperion.law
            - name: FOUNDRY_IP_DISCOVERY
              value: "false"
            - name: FOUNDRY_PROXY_SSL
              value: "true"
            - name: FOUNDRY_ROUTE_PREFIX
              value: edgerunners
          ports:
            - name: http
              containerPort: 30000
          volumeMounts:
            - name: data
              mountPath: /data
          securityContext:
            fsGroup: 421
            runAsUser: 421
            runAsGroup: 421
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: edgerunners-data