apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundryvtt-edgerunners
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: foundryvtt
    foundryvtt/world: edgerunners
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: foundryvtt
      foundryvtt/world: edgerunners
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foundryvtt
        foundryvtt/world: edgerunners
    spec:
      securityContext:
        fsGroup: 421
        runAsUser: 421
        runAsGroup: 421
      serviceAccountName: foundryvtt
      containers:
        - name: foundryvtt-edgerunners
          image: trow.hyperion.law/foundryvtt:10.291.0
          envFrom:
            - secretRef:
                name: foundryvtt-secrets
          env:
            - name: FOUNDRY_HOSTNAME
              value: foundry.hyperion.law
            - name: FOUNDRY_IP_DISCOVERY
              value: "false"
            - name: FOUNDRY_PROXY_SSL
              value: "true"
            - name: FOUNDRY_ROUTE_PREFIX
              value: edgerunners
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /data
          securityContext:
            add:
              - CHOWN
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: edgerunners-data