apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundryvtt-edgerunners
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: foundryvtt
    foundryvtt/world: edgerunners
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: foundryvtt
      foundryvtt/world: edgerunners
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foundryvtt
        foundryvtt/world: edgerunners
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
      containers:
        - name: foundryvtt-edgerunners
          image: trow.hyperion.law/foundryvtt:10.291
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 30000
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /home/foundry/data/Config/options.json
              subPath: options.json
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: edgerunners-data
        - name: config
          configMap:
            name: edgerunners-cm