apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: londolas-data
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
