apiVersion: v1
kind: Service
metadata:
  name: foundryvtt-londolas
  labels:
    app.kubernetes.io/name: foundryvtt
    foundryvtt/world: londolas
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 30000
      targetPort: http
  selector:
    app.kubernetes.io/name: foundryvtt
    foundryvtt/world: londolas