apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundryvtt-londolas
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: foundryvtt
    foundryvtt/world: londolas
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: foundryvtt
      foundryvtt/world: londolas
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: foundryvtt
        foundryvtt/world: londolas
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 421
      containers:
        - name: foundryvtt-londolas
          image: trow.hyperion.law/foundryvtt:10.291.0
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: foundryvtt-secrets
          env:
            - name: FOUNDRY_HOSTNAME
              value: foundry.hyperion.law
            - name: FOUNDRY_IP_DISCOVERY
              value: "false"
            - name: FOUNDRY_PROXY_SSL
              value: "true"
            - name: FOUNDRY_ROUTE_PREFIX
              value: londolas
            - name: NODE_EXTRA_CA_CERTS
              value: /usr/local/share/ca-certificates/law-ca.crt
          ports:
            - name: http
              containerPort: 30000
          volumeMounts:
            - name: data
              mountPath: /data
          securityContext:
            runAsUser: 421
            runAsGroup: 421
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: londolas-data