kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:0-foundryvtt
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - 0-foundryvtt