apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: foundryvtt-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: foundryvtt-secrets
  data:
    - secretKey: FOUNDRY_ADMIN_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /foundryvtt
        property: password
    - secretKey: FOUNDRY_LICENSE_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /foundryvtt
        property: license
