apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stats_db
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
