apiVersion: v1
kind: Service
metadata:
  name: spotify-stats
  namespace: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: spotify-stats
  ports:
    - name: web-http
      protocol: TCP
      port: 3000
      targetPort: web-http
    - name: api-http
      protocol: TCP
      port: 8080
      targetPort: api-http
      