apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spotify-stats-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: spotify-stats-secrets
  data:
    - secretKey: SPOTIFY_PUBLIC
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /spotify
        property: client_id
    - secretKey: SPOTIFY_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /spotify
        property: client_secret
