kube-prometheus-stack:
  defaultRules:
    rules:
      etcd: false

  kubeEtcd:
    enabled: false

  kubeControllerManager:
    enabled: true
    endpoints: ['20.10.1.3']
    service:
      enabled: true
      port: 10257
      targetPort: 10257
    serviceMonitor:
      enabled: true
      https: true

  kubeScheduler:
    enabled: true
    endpoints: ['20.10.1.3']
    service:
      enabled: true
      port: 10259
      targetPort: 10259
    serviceMonitor:
      enabled: true
      https: true

  kubeProxy:
    enabled: true
    endpoints: ['20.10.1.3']
    service:
      enabled: true
      port: 10249
      targetPort: 10249
    serviceMonitor:
      enabled: true
      https: false

  grafana:
    adminPassword: null
    ingress:
      enabled: false
    #  ingressClassName: nginx
    #  annotations:
    #    #cert-manager.io/cluster-issuer: letsencrypt-prod
    #    hajimari.io/appName: Grafana
    #    hajimari.io/icon: chart-bar
    #  hosts:
    #    - &host grafana.khuedoan.com
    #  tls:
    #    - secretName: grafana-general-tls
    #      hosts:
    #        - *host
    additionalDataSources:
      - name: Loki
        type: loki
        url: http://loki.loki:3100
    envFromSecret: grafana-secrets
    grafana.ini:
      server:
        root_url: https://grafana.hyperion.law
      auth.generic_oauth:
        enabled: true
        allow_sign_up: true
        name: Dex
        client_id: grafana-sso
        client_secret: $__env{GRAFANA_SSO_CLIENT_SECRET}
        scopes: openid profile email groups
        auth_url: https://dex.hyperion.law/auth
        token_url: https://dex.hyperion.law/token
        api_url: https://dex.hyperion.law/userinfo

  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
