---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-loki-memberlist
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: loki-memberlist
      app.kubernetes.io/instance: loki
  ingress:
  - ports:
    - port: 7946
      protocol: TCP
  policyTypes:
  - Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-loki-headless
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: loki-headless
      app.kubernetes.io/instance: loki
  ingress:
  - ports:
    - port: 3100
      protocol: TCP
  policyTypes:
  - Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-loki
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: loki
      app.kubernetes.io/instance: loki
  ingress:
  - ports:
    - port: 3100
      protocol: TCP
  policyTypes:
  - Ingress
