---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex-tls-certificate
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  commonName: dex.hyperion.law
  secretName: dex-tls-certificate
  dnsNames:
    - dex.hyperion.law
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer