apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=false
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: dex-secrets
  data:
    - secretKey: LDAP_BIND_PASSWORD
      remoteRef:
        key: /ldap/admin
        property: password
    - secretKey: GRAFANA_SSO_CLIENT_SECRET
      remoteRef:
        key: /dex/grafana
        property: client_secret
