apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: onedev
    version: 7.9.4
    repo: https://dl.cloudsmith.io/public/onedev/onedev/helm/charts
    releaseName: onedev
    namespace: onedev
    valuesFile: values.yaml
patchesStrategicMerge:
  - deletesqlsecret.yaml
patches:
  - addfsgroup.yaml
resources:
  - ingressroute.yaml
  - certificate.yaml
  - secret.yaml