apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:0-onedev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:0-onedev
subjects:
  - kind: ServiceAccount
    name: onedev