apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:onedev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:onedev
subjects:
  - kind: ServiceAccount
    name: onedev