apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: onedev-secrets
  namespace: onedev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: onedev-secrets
  data:
    - secretKey: initial_password
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: /ldap/admin
        property: password