apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
    hajimari.io/appName: Grafana
    hajimari.io/icon: chart-bar
spec:
  entryPoints:
    - websecure
  tls:
    secretName: grafana-general-tls
  routes:
    - match: Host(`grafana.hyperion.law`)
      kind: Rule
      services:
        - name: grafana
          port: http-web
          kind: Service