apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-policy
  namespace: {{ .Release.Namespace }}
spec:
  ingress:
  - ports:
    - port: 80
      protocol: TCP
    from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: traefik
  podSelector:
    matchLabels:
      app.kubernetes.io/name: grafana
  policyTypes:
  - Ingress