apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: longhorn-conversion-webhook
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: longhorn-conversion-webhook
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 9443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: longhorn-admission-webhook
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: longhorn-admission-webhook
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 9443