dex:
  config:
    issuer: https://dex.hyperion.law
    storage:
      type: kubernetes
      config:
        inCluster: true
    oauth2:
      skipApprovalScreen: true
    connectors:
      - type: ldap
        id: ldap
        name: LDAP
        config:
          host: openldap.openldap:1636
          rootCA: /etc/ssl/certs/law-ca.pem
          bindDN: cn=admin,dc=hyperion,dc=law
          bindPW: $LDAP_BIND_PASSWORD
          userSearch:
            baseDN: ou=users,dc=hyperion,dc=law
            username: uid
            idAttr: uid
            emailAttr: uid
            nameAttr: uid
            preferredUsernameAttr: uid
    staticClients:
      - id: grafana-sso
        name: Grafana
        redirectURIs:
          - 'https://grafana.hyperion.law/login/generic_oauth'
        secretEnv: GRAFANA_SSO_CLIENT_SECRET
      - id: onedev-sso
        name: OneDev
        redirectURIs:
          - 'https://onedev.hyperion.law/~sso/callback/Dex'
        secretEnv: ONEDEV_SSO_CLIENT_SECRET
  envFrom:
    - secretRef:
        name: dex-secrets
  ingress:
    enabled: false
  volumes:
    - name: law-ca
      configMap:
        name: law-ca
  volumeMounts:
    - name: law-ca
      mountPath: /etc/ssl/certs/law-ca.pem
      subPath: law-ca.pem