---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-tls-certificate
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  commonName: alertmanager.hyperion.law
  secretName: alertmanager-tls-certificate
  dnsNames:
    - alertmanager.hyperion.law
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer