apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: kured
    version: 4.2.0
    repo: https://kubereboot.github.io/charts
    releaseName: kured
    namespace: kured
    valuesFile: values.yaml
patches:
  - psppatch.yaml