trow:
  trow:
    domain: registry.hyperion.law
    # user: user
    # password: password
    validation:
      enabled: false
      allowDocker: false
      allowKubernetes: true
      allowPrefixes: []
      allowImages: []
      disallowLocalPrefixes: []
      disallowLocalImages: []
      proxyDockerHub: false

  ingress:
    enabled: false
  volumeClaim:
    storageClassName: longhorn
