gitea:
  ingress:
    enabled: false
  gitea:
    admin:
      existingSecret: gitea-admin-secret
    config:
      server:
        LANDING_PAGE: explore
        ROOT_URL: https://git.hyperion.law
  persistence:
    storageClass: longhorn
  postgresql:
    persistence:
      storageClass: longhorn
