---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trow-tls-certificate
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  commonName: trow.hyperion.law
  secretName: trow-tls-certificate
  dnsNames:
    - trow.hyperion.law
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer