---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trow-tls-certificate
  namespace: {{ .Release.Namespace }}
spec:
  commonName: trow.hyperion.law
  secretName: trow-tls-certificate
  dnsNames:
    - trow.hyperion.law
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer