---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-external-secrets-webhook
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: external-secrets-webhook
      app.kubernetes.io/instance: external-secrets
  ingress:
  - ports:
    - port: 443
      protocol: TCP
    - port: 10250
      protocol: TCP
  policyTypes:
  - Ingress
