---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tls-certificate
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  commonName: longhorn.hyperion.law
  secretName: longhorn-tls-certificate
  dnsNames:
    - longhorn.hyperion.law
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer