---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tls-certificate
  namespace: {{ .Release.Namespace }}
spec:
  commonName: longhorn.hyperion.law
  secretName: longhorn-tls-certificate
  dnsNames:
    - longhorn.hyperion.law
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer