apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap-tls-certificate
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  commonName: ldap.hyperion.law
  secretName: openldap-tls-certificate
  dnsNames:
    - ldap.hyperion.law
    - openldap
    - openldap.openldap
    - openldap.openldap.svc
    - openldap.openldap.svc.cluster.local
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer