apiVersion: apps/v1
kind: Deployment
metadata:
  name: openldap
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap:latest
          imagePullPolicy: "Always"
          envFrom:
            - secretRef:
                name: openldap-secrets
          env:
            - name: LDAP_ADMIN_USERNAME
              value: admin
            - name: LDAP_ROOT
              value: dc=hyperion,dc=law
            - name: LDAP_ENABLE_TLS
              value: "yes"
            - name: LDAP_TLS_CERT_FILE
              value: /opt/bitnami/openldap/certs/tls.crt
            - name: LDAP_TLS_CA_FILE
              value: /opt/bitnami/openldap/certs/ca.crt
            - name: LDAP_TLS_KEY_FILE
              value: /opt/bitnami/openldap/certs/tls.key
            - name: LDAP_SKIP_DEFAULT_TREE
              value: "yes"
            - name: LDAP_CUSTOM_LDIF_DIR
              value: /ldif
          ports:
            - name: tls-ldap
              containerPort: 1636
          volumeMounts:
            - name: tls
              mountPath: /opt/bitnami/openldap/certs
            - name: ldifs
              mountPath: /ldif
      volumes:
        - name: tls
          secret:
            secretName: openldap-tls-certificate
        - name: ldifs
          secret:
            secretName: openldap-ldifs
