apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ldap-ingress
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - ldap
  routes:
    - match: HostSNI(`*`)
      services:
        - name: openldap
          port: tls-ldap
  tls:
    passthrough: true
