apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openldap-secrets
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: openldap-secrets
  data:
    - secretKey: LDAP_ADMIN_PASSWORD
      remoteRef:
        key: /ldap/admin
        property: password
    - secretKey: LDAP_PASSWORDS
      remoteRef:
        key: /ldap/users
        property: j