apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openldap-ldifs
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: openldap-ldifs
    template:
        engineVersion: v2
        templateFrom:
          - target: Data
            literal: |
              0-domain.ldif: |
{{ .Files.Get "files/domain.ldif" | indent 16 }}
              1-ou.ldif: |
{{ .Files.Get "files/ou.ldif" | indent 16 }}
              {{`{{ range $key, $value := . }}
              2-{{ $key }}-user.ldif: |
                dn: cn={{ $key }},ou=users,dc=hyperion,dc=law
                changetype: add
                cn: {{ $key }}
                uid: {{ $key }}
                sn: {{ $key }}
                mail: {{ $key }}@hyperion.law
                objectclass: inetorgperson
                objectclass: top
                userPassword: {{ $value }}
              {{ end }}`}}
      
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: /ldap/users
