kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-webhook
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/name: webhook
  ingress:
  - ports:
    - port: 443
      protocol: TCP
  policyTypes:
  - Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-webhook
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: cert-manager
      app.kubernetes.io/name: cert-manager
  ingress:
  - ports:
    - port: 9402
      protocol: TCP
  policyTypes:
  - Ingress
