apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: http://vault.vault:8200
      path: secret
      caProvider:
        type: Secret
        namespace: cert-manager
        name: internal-ca
        key: tls.crt
      auth:
        kubernetes:
          mountPath: kubernetes
          role: default
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
