apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    hajimari.io/appName: alertmanager
    hajimari.io/icon: chart-bar
spec:
  entryPoints:
    - websecure
  tls:
    secretName: alertmanager-tls-certificate
  routes:
    - match: Host(`alertmanager.hyperion.law`)
      kind: Rule
      services:
        - name: {{ .Release.Namespace }}-kube-prometheus-alertmanager
          port: http-web
          kind: Service