---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls-certificate
  namespace: {{ .Release.Namespace }}
spec:
  commonName: grafana.hyperion.law
  secretName: grafana-tls-certificate
  dnsNames:
    - grafana.hyperion.law
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer