---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls-certificate
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  commonName: prometheus.hyperion.law
  secretName: prometheus-tls-certificate
  dnsNames:
    - prometheus.hyperion.law
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer