---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls-certificate
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  commonName: vault
  secretName: vault-tls-certificate
  dnsNames:
    - vault
    - vault.vault
    - vault.vault.svc
    - vault.vault.svc.cluster.local
    - vault.hyperion.law
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer