---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls-certificate
  namespace: {{ .Release.Namespace }}
spec:
  commonName: vault
  secretName: vault-tls-certificate
  dnsNames:
    - vault
    - vault.vault
    - vault.vault.svc
    - vault.vault.svc.cluster.local
    - vault.hyperion.law
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer