apiVersion: batch/v1
kind: Job
metadata:
  name: generate-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: apply
          imagePullPolicy: Never
          image: generate-secrets:latest
          env:
            - name: VAULT_ADDR
              value: https://vault:8200
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-unseal-keys
                  key: vault-root
          volumeMounts:
            - mountPath: /etc/ssl/certs/vault-ca.pem
              subPath: vault-ca.pem
              name: vault-tls
            - mountPath: /config.yaml
              subPath: config.yaml
              name: secret-list
      volumes:
        - name: vault-tls
          secret:
            secretName: vault-tls
            items:
              - key: ca.crt
                path: vault-ca.pem
        - name: secret-list
          configMap:
            name: generate-secrets
            items:
              - key: secrets
                path: config.yaml