apiVersion: batch/v1
kind: Job
metadata:
  name: generate-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: apply
          image: golang:1.17-alpine
          env:
            - name: VAULT_ADDR
              value: https://vault:8200
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-unseal-keys
                  key: vault-root
            - name: HTTP_PROXY
              value: http://10.10.2.1:3128/
            - name: HTTPS_PROXY
              value: http://10.10.2.1:3128/
            - name: NO_PROXY
              value: localhost,127.0.0.1,::1,vault
          workingDir: /go/src/generate-secrets
          command:
            - sh
            - -c
          args:
            - |
              go get .
              go run .
          volumeMounts:
            - name: source
              mountPath: /go/src/generate-secrets
            - mountPath: /etc/ssl/certs/law-ca.pem
              subPath: law-ca.pem
              name: law-ca
      volumes:
        - name: source
          configMap:
            name: generate-secrets-source
        - configMap:
            name: law-ca
          name: law-ca