apiVersion: v1
kind: ConfigMap
metadata:
  name: generate-secrets
  namespace: {{ .Release.Namespace }}
data:
  secrets: |
    # Dex
    - path: dex/grafana
      data:
        - key: client_secret
          length: 32
          special: false
  
    - path: dex/onedev
      data:
        - key: client_secret
          length: 32
          special: false

    # Trow
    - path: trow/admin
      data:
        - key: password
          length: 32
          special: true

    # OpenLDAP
    - path: ldap/admin
      data:
        - key: password
          length: 32
          special: false
    
    - path: ldap/users
      data:
        - key: j
          length: 32
          special: false