apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vault-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    hajimari.io/appName: Vault
    hajimari.io/icon: database-lock
spec:
  entryPoints:
    - websecure
  tls:
    spassthrough: true
  routes:
    - match: HostSNI(`vault.hyperion.law`)
      kind: Rule
      services:
        - name: vault
          port: 8200
          kind: Service
 