apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    hajimari.io/appName: Vault
    hajimari.io/icon: database-lock
spec:
  entryPoints:
    - websecure
  tls:
    secretName: vault-tls-certificate
  routes:
    - match: Host(`vault.hyperion.law`)
      kind: Rule
      services:
        - name: vault
          kind: Service
          port: 8200
          scheme: https
          serversTransport: vault-ingress-transport

---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: vault-ingress-transport
  namespace: {{ .Release.Namespace }}
spec:
  insecureSkipVerify: true
