apiVersion: batch/v1
kind: CronJob
metadata:
  name: generate-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  schedule: '*/5 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: apply
              image: golang:1.17-alpine
              env:
                - name: VAULT_ADDR
                  value: http://vault:8200
                - name: VAULT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: vault-unseal-keys
                      key: vault-root
                - name: HTTP_PROXY
                  value: http://10.10.2.1:3128/
                - name: HTTPS_PROXY
                  value: http://10.10.2.1:3128/
                - name: NO_PROXY
                  value: localhost,127.0.0.1,::1,.hyperion.law,.svc,.cluster.local,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,10.10.1.0/24,10.10.2.0/24,20.10.1.0/24,10.42.0.0/24
              workingDir: /go/src/generate-secrets
              command:
                - sh
                - -c
              args:
                - |
                  go get .
                  go run .
              volumeMounts:
                - name: source
                  mountPath: /go/src/generate-secrets
                - mountPath: /etc/ssl/certs/law-ca.pem
                  subPath: law-ca.pem
                  name: law-ca
          volumes:
            - name: source
              configMap:
                name: generate-secrets-source
            - configMap:
                name: law-ca
              name: law-ca
